spring:
  config:
    import: "configserver:"
  application:
    name: licensing-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071

  messages:
    basename: messages         # messages.properties, messages_ko.properties ?? ???? ??
    encoding: UTF-8            # ??? ?? ???
  web:
    locale: en
    locale-resolver: accept_header

logging:
  level:
    org.springframework.web: WARN
    com.optimagrowth: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      licenseService:
        registerHealthIndicator: true
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
      organizationService:
        registerHealthIndicator: true
        sliding-window-size: 6
        permitted-number-of-calls-in-half-open-state: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 60

  bulkhead:
    instances:
      bulkheadLicenseService:
        max-wait-duration: 10ms
        max-concurrent-calls: 20

  thread-pool-bulkhead:
    instances:
      bulkheadLicenseService:
        max-thread-pool-size: 1
        core-thread-pool-size: 1
        queue-capacity: 1
        keep-alive-duration: 20ms

  retry:
    instances:
      retryLicenseService:
        max-attempts: 5
        waitDuration: 10000
        retry-exceptions:
          - java.util.concurrent.TimeoutException

  ratelimiter:
    instances:
      licenseService:
        timeout-duration: 1000ms
        limit-refresh-period: 5000
        limit-for-period: 5